services:
  - type: web
    name: ap-score-tracker
    env: node
    buildCommand: npm install
    startCommand: npm run db:init && npm start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: JWT_SECRET
        generateValue: true
      - key: BASE_URL
        fromService:
          type: web
          name: ap-score-tracker
          property: host
      - key: GOOGLE_CALLBACK_URL
        fromService:
          type: web
          name: ap-score-tracker
          property: host
        suffix: /api/auth/google/callback

databases:
  - name: ap-tracker-db
    databaseName: ap_tracker
    user: ap_tracker
